### PR TITLE
WIP: Python Implementation of Cards

### PR DESCRIPTION
**Pull request by agroener**
This PR is a work in progress. Please do not merge until the WIP qualifier is removed from the title.

A pure python implementation of our cards may be useful for some of the RL/DL prototyping we plan to do. This will decouple us a bit from the on-going engine work that will be done.

### CODE REVIEW

**Comment by agroener** [comment]
Item 1: Make sure I didn't mess up something here (names, inheritance, etc).
Item 2: Is it cool if we separate out cards with different mechanics into different files?

TODO: A lot left to implement here.

**Comment by codpro880** [comment]
An alternative is to wrap the C++ in some CLI/JSON interface that enables the interaction you're looking for. Could help save some work. Another alternative is pybind11. Yes, the engine is changing, but the card mechanics and battle sim are stable enough that a wrapper layer should be okay (whether it's JSON or pybind11 to expose in python directly, or both)

All that said, a pure Python impl seems fine to me if you want to go that route.

**Comment by agroener** [comment]
> An alternative is to wrap the C++ in some CLI/JSON interface that enables the interaction you're looking for. Could help save some work. Another alternative is pybind11. Yes, the engine is changing, but the card mechanics and battle sim are stable enough that a wrapper layer should be okay (whether it's JSON or pybind11 to expose in python directly, or both)
> 
> All that said, a pure Python impl seems fine to me if you want to go that route.

Appreciate you laying out the options here. I'm not 100% sure what the best way forward is, but I can just say that my objective with starting on a pure python implementation of this was to get going as soon as possible on the per-matchup predictive model (think providing poker odds (but obviously we need to try and predict this in real-time since there is randomness and way more options than in poker)). 

**Pros vs. Cons to a Python Impl:**
Pro: We don't have to wait until someone wraps anything.
Con: Am I really suggesting we maintain two versions of the same code? :-D We've had long discussions about how insane this is.
Pro/Con: It's a bunch of tedious work, but it shouldn't take too long (since you already have the object-oriented framework laid out).
Pro: Python has a bit less overhead than C++, plus we can do things interactively from the get-go (w/o needing to wrap).
Con: It'll probably be slower. Not sure by how much really, as we're not really doing anything computationally intensive here. You could also perhaps argue that the speed won't be an issue in certain situations (if you were working not the per-matchup (1v1) model, you could run lots of realizations of this matchup in parallel).

**Comment by codpro880** [comment]
I was thinking, since you've already contributed to the c++ baseline and you've seen it's not _complete_ garbage, and that it's clear folks can contribute to it since you've already done it, I'm wondering if you're leaning towards a wrapping solution like I am? I do understand why a pure python solution makes sense, but I am mostly looking to avoid work/maintenance. I feel the wrapping is just a shorter put b/c the C++ baseline is in decent shape. In particular, passing JSON to and fro seems like the easiest thing to impl at the moment. Us ex-Lockheeders tend to be scared of C++ b/c we know it can be a mess, but I think we can all agree this is not the typical C/C++98 mix-mash that we're used to.

 @aecallahan is looking for a CLI tool anyway, I'm thinking this tool could be a python script that passes JSON. I'm certainly willing to help on this wrapping front, but I'd still like to stay focused on the sim functionality as my #1 goal. Could you or @aecallahan  lead this charge?

**Comment by agroener** [comment]
Agree with you Matt. Now that I've worked with the code a bit, I think we should go the wrapping route, too. I'm happy to lead this work.

As for ideas about how to wrap: did I hear you and Frank correctly in regards to PyBind11? I will take a look at that first.

**Pull request closed without merging**
